### ISSUE TITLE
OpenGL error 1281 or 1282

### ISSUE THREAD

**Issue by Pathoschild** [Steviegt6/Stardew64Installer#32]
Some users report `MonoGameGLException: GL.GetError() returned 1281` or `1282` errors when mods edit textures. This is relatively rare but there's no known fix, so this ticket tracks the known info,

## Sample error
```
[Content Patcher] Unhandled exception applying patch: Trypophobia > EditImage Maps\fall_beach #1.
Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned 1281
   at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError()
   at Microsoft.Xna.Framework.Graphics.Texture2D.<PlatformSetData>c__AnonStorey1`1.<>m__0()
   at Microsoft.Xna.Framework.Threading.BlockOnUIThread(Action action)
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](Int32 level, Int32 arraySlice, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at StardewModdingAPI.Framework.Content.AssetDataForImage.PatchImage_PatchedBy<Platonymous.PyTK>(Object source, Texture2D sourceArea, Nullable`1 targetArea, Nullable`1 patchMode, PatchMode )
   at ContentPatcher.Framework.Patches.EditImagePatch.Edit[T](IAssetData asset) in C:\source\_Stardew\Mods.Pathoschild\Common\Items\ItemRepository.cs:line 291
   at ContentPatcher.Framework.PatchManager.Edit[T](IAssetData asset) in C:\source\_Stardew\Mods.Pathoschild\ContentPatcher\Framework\Tokens\ValueProviders\ManualValueProvider.cs:line 61
```

[OpenGL error descriptions](https://www.khronos.org/opengl/wiki/OpenGL_Error) for 1281 (`0x0501`) and 1282 (`0x0502`):
> GL_INVALID_VALUE, 0x0501
> Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
> 
> GL_INVALID_OPERATION, 0x0502
> Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.

### Error 1281
* Most players never see this error.
* Affected users generally see the error every time they play, but it can affect different mods or textures each time.
* Affected textures are [shown as black blocks in-game](https://user-images.githubusercontent.com/230581/128573407-b6cd9e5d-134a-4bfe-bbfb-308cd4eeaaa9.png).
* This portion of the stack trace seems to be consistent for all such errors:
  ```
  at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.CheckGLError()
  at Microsoft.Xna.Framework.Graphics.Texture2D.<PlatformSetData>c__AnonStorey1`1.<>m__0()
  at Microsoft.Xna.Framework.Threading.BlockOnUIThread(Action action)
  at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](Int32 level, Int32 arraySlice, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
  at StardewModdingAPI.Framework.Content.AssetDataForImage.PatchImage_PatchedBy<Platonymous.PyTK>(Object source, Texture2D sourceArea, Nullable`1 targetArea, Nullable`1 patchMode, PatchMode )
  ```

### Error 1282
This is possibly related to 1281, but not enough reports yet to see patterns.

### Error 1281
user | log | Win | SMAPI | patcher | notes
---- | --- | --- | ----- | ------- | -------------
Fri 2021-08-06<br />[marry481](https://www.nexusmods.com/stardewvalley/mods/1915/?tab=posts) | [log](https://smapi.io/log/c409dc57e24b4771979ea79021402cd9) | 10 | 3.12.2 | 1.1.8 | Affects Content Patcher. Has PyTK.
Thu 2021-07-29<br />acearohippo (Saelym) on Discord | [A](https://smapi.io/log/266d9e51b5ef4b07bbea591f19bc6b32), [B](https://smapi.io/log/1102584119bc4828b473d90c0ac4e334) | 10 | 3.11.0 | 1.1.8 | Affects Content Patcher, Lunar Disturbances, Walk of Life. Has PyTK.
Mon 2021-06-21<br />Nari on Discord | n/a | ? | ? | ? | Attempted fixes: updated graphics drivers.
Tue 2021-05-04<br />Zilch on Discord | n/a | ? | ? | ? | 

### Error 1282
user | log | Win | SMAPI | patcher | notes
---- | --- | --- | ----- | ------- | -------------
Sun 2021-08-08<br />PurrplingCat on Discord | [log](https://smapi.io/log/afa8624dbd8c48dbaa7faaf52b6bad57) | 10 | 3.12.2 | 1.1.8 | Affects NPC Adventures.
Thu 2021-06-17<br />Wingheart on Discord | n/a | ? | ? | ? | Affects SpriteMaster.

**Comment by steviegt6** [comment]
It'd be valuable to get information on system hardware, especially given that this remains seemingly consistent for all affected users.
